---
driver:
  name: vagrant
  forward_agent: true
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[g5-orion-vagrant::default]
    attributes:
      postgresql:
        password:
          postgres: 'password'
      git:
        user:
          name: <%= `git config user.name`.strip %>
          email: <%= `git config user.email`.strip %>
