---
driver:
  name: vagrant
  forward_agent: true
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[g5-orion-vagrant::default]
    attributes:
