default['mozilla-firefox']['version'] = '31.5.0esr'

default['rbenv']['ruby_versions'] = []

default['g5-orion-vagrant']['env']['secret_token'] = SecureRandom.hex(64)
default['g5-orion-vagrant']['env']['g5_configurator_webhook_url'] = 'http://g5-configurator.herokuapp.com/consume_feed'
default['g5-orion-vagrant']['env']['heroku_app_name'] = 'not-a-heroku-app'
default['g5-orion-vagrant']['env']['app_display_name'] = 'G5 Client App Updater'
default['g5-orion-vagrant']['env']['g5_hub_port'] = '3001'
default['g5-orion-vagrant']['env']['g5_configurator_port'] = '3002'
default['g5-orion-vagrant']['env']['g5_client_app_creator_port'] = '3003'
default['g5-orion-vagrant']['env']['g5_layout_garden_port'] = '3004'
default['g5-orion-vagrant']['env']['g5_theme_garden_port'] = '3005'
default['g5-orion-vagrant']['env']['g5_widget_garden_port'] = '3006'
default['g5-orion-vagrant']['env']['g5_sibling_deployer_port'] = '3007'
default['g5-orion-vagrant']['env']['g5_content_management_system_port'] = '3008'
default['g5-orion-vagrant']['env']['g5_phone_number_service_port'] = '3009'
default['g5-orion-vagrant']['env']['g5_pricing_and_availability_port'] = '3010'
default['g5-orion-vagrant']['env']['heroku_api_key'] = ''
default['g5-orion-vagrant']['env']['heroku_username'] = ''
default['g5-orion-vagrant']['env']['id_rsa'] = ''
default['g5-orion-vagrant']['env']['heroku_repo'] = ''
default['g5-orion-vagrant']['env']['github_repo'] = ''
default['g5-orion-vagrant']['env']['aws_access_key_id'] = ''
default['g5-orion-vagrant']['env']['aws_secret_access_key'] = ''
default['g5-orion-vagrant']['env']['aws_region'] = ''
